{ config, lib, pkgs, ... }:

let
  cfg = config.ringofstorms.plymouth;

  # Resolve the KMS modules to force-load in initrd. If the user
  # explicitly set earlyKms (including to []) we honour that; otherwise
  # we infer from services.xserver.videoDrivers. The auto-derive matters
  # most for AMD / NVIDIA hosts: missing the right module here is the #1
  # cause of "the splash sometimes drops to text logs" in this repo.
  resolvedEarlyKms =
    if cfg.earlyKms != null then cfg.earlyKms
    else
      let v = config.services.xserver.videoDrivers or [ ];
      in
        if builtins.elem "amdgpu" v then [ "amdgpu" ]
        else if builtins.elem "nvidia" v then
          [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ]
        else [ "i915" ];

  # ---------------------------------------------------------------------------
  # Neon snowflake frame generator.
  #
  # Pipeline (all at Nix build time; nothing prerendered is committed):
  #
  #   1. Rasterize four SVGs with resvg:
  #        - snowflake-mask.svg       → full silhouette (used for halo + framing)
  #        - snowflake-arms-dark.svg  → silhouette of the three "dark" arms only
  #        - snowflake-arms-light.svg → silhouette of the three "light" arms only
  #        - circuits.svg             → dim PCB-trace backdrop (6-fold symmetric)
  #      The snowflake is rendered at ~62% of the canvas width so the
  #      circuits ring it rather than overlapping it. (Earlier values
  #      of 53% read as "small object on big canvas"; 62% gives the
  #      snowflake more presence without crowding the circuits.)
  #
  #   2. Build a static "background" PNG: dark canvas (#0a0a0c) with the
  #      circuits centered on it. This never changes between frames, so
  #      we build it once and reuse.
  #
  #   3. Build a static "neon" PNG: per-arm-class gradient tubes plus a
  #      soft outer halo. The trick is that flat fills + a glow halo
  #      read as "orange sticker on dark background" rather than as a
  #      glowing tube — so each arm is recolored by a *distance
  #      transform* gradient (edge of arm → deeper interior maps to
  #      darker → brighter orange). Two distinct gradients are used:
  #          dark arms : #2a0700 → #F24005   (deep, redder)
  #          light arms: #5a1a02 → #FF8030   (bright, hotter)
  #      Both endpoints stay strictly in the orange/red hue range — no
  #      white or pale amber, which would wash to gray-white when
  #      screen-blended with the halo. The two-tone differentiation
  #      gives back the alternating-arm structure of the original NixOS
  #      logo without losing the neon look.
  #
  #      Halo is one tinted-blurred copy of the full silhouette,
  #      screen-blended underneath the tubes. Sigma 12 + 0.40 alpha
  #      keeps it tight to the snowflake without bleeding into the
  #      circuits.
  #
  #   4. For each frame:
  #        a. Take the neon layer, multiply its RGB by the frame's
  #           brightness factor `m` (1.0 = on, ≤1.0 = dimmed flicker),
  #           keeping its alpha channel intact. `-channel RGB` scopes
  #           the multiply to color channels only — multiplying alpha
  #           too would shrink the snowflake during a flicker (wrong
  #           perceptual effect for a buzzing tube; we want it to dim
  #           in place, not shrink).
  #        b. Composite the dimmed neon over the background.
  #        c. Run pngquant for size.
  #
  #   5. Flicker schedule is generated by an awk loop and is deterministic
  #      (seeded from the frame index) so rebuilds of the same source SVGs
  #      produce byte-identical PNGs — important for nix store reuse.
  #      Schedule profile: 90% of frames steady at 1.0, occasional 1–2
  #      frame dips to 0.85 / 0.7 / 0.55, very rare 1-frame near-blackout
  #      at 0.25. Mimics a real failing neon sign rather than constant
  #      strobing.
  #
  # The output is a directory of frame-XXXX.png files which the theme
  # derivation copies into the Plymouth theme dir alongside the .script.
  # ---------------------------------------------------------------------------
  infiniteFrames = pkgs.runCommand "infinite-frames"
    {
      nativeBuildInputs = [ pkgs.resvg pkgs.imagemagick pkgs.pngquant pkgs.gawk ];
      passAsFile = [ "maxWidth" "frameCount" ];
      maxWidth   = toString cfg.maxWidth;
      frameCount = toString cfg.frameCount;
    } ''
      set -euo pipefail
      mkdir -p $out
      maxw=$(cat $maxWidthPath)
      nframes=$(cat $frameCountPath)

      # Snowflake takes ~62% of canvas width so the circuits (which
      # extend nearly to the SVG edge) frame it without crowding.
      sw=$(( maxw * 62 / 100 ))

      # ---------- 1. Rasterize SVGs ----------
      resvg --width "$maxw" ${./assets/circuits.svg}             circuits.png
      resvg --width "$sw"   ${./assets/snowflake-mask.svg}       mask.png
      resvg --width "$sw"   ${./assets/snowflake-arms-dark.svg}  arms-dark.png
      resvg --width "$sw"   ${./assets/snowflake-arms-light.svg} arms-light.png

      # Pad to maxw×maxw on transparent background, centered, so every
      # layer shares dimensions for clean compositing.
      magick mask.png       -background none -gravity center -extent "''${maxw}x''${maxw}" mask-c.png
      magick arms-dark.png  -background none -gravity center -extent "''${maxw}x''${maxw}" dark-c.png
      magick arms-light.png -background none -gravity center -extent "''${maxw}x''${maxw}" light-c.png

      # ---------- 2. Background (dark canvas + circuits) ----------
      # `-compose over` is the default but we name it explicitly because
      # the rest of the pipeline switches between operators.
      magick -size "''${maxw}x''${maxw}" canvas:'#0a0a0c' \
        circuits.png -gravity center -compose over -composite \
        background.png

      # ---------- 3. Neon stack ----------
      # Two-tone gradient tubes + a single soft halo. See the long
      # comment at the top of this file for the why.

      # Helper: build a colored tube layer from one arm-class silhouette.
      #   $1 = input mask png, $2 = output png,
      #   $3 = edge color (deep), $4 = inner color (bright)
      # Steps:
      #   - distance transform inside the silhouette → grayscale where
      #     deeper interior = brighter
      #   - colorize via gradient CLUT (must promote distance to sRGB
      #     first, otherwise CLUT collapses to grayscale)
      #   - reattach the original binary mask as alpha so the tube is
      #     fully opaque inside the silhouette and the *color* varies
      #     by depth (NOT the alpha — varying alpha would let the dark
      #     background bleed through and the snowflake would look
      #     hollow/translucent rather than glowing)
      make_tube() {
        local in="$1" out="$2" cedge="$3" cinner="$4"
        magick "$in" -alpha extract \
          -morphology Distance Euclidean:4 \
          -auto-level dist.png
        magick -size 1x256 "gradient:''${cedge}-''${cinner}" -colorspace sRGB grad.png
        magick dist.png -colorspace sRGB grad.png -clut tube-rgb.png
        magick "$in" -alpha extract mask-a.png
        magick tube-rgb.png mask-a.png \
          -compose CopyOpacity -composite \
          -define png:color-type=6 \
          "$out"
      }

      # Dark arms: deeper, redder gradient (#f24005 family)
      make_tube dark-c.png  tube-dark.png  '#2a0700' '#F24005'
      # Light arms: brighter, hotter gradient
      make_tube light-c.png tube-light.png '#5a1a02' '#FF8030'

      # Halo: tight outer aura, kept off the circuits.
      magick mask-c.png \
        -filter Gaussian -blur 0x12 \
        +level-colors "black,#FF5A00" \
        -channel A -evaluate Multiply 0.40 +channel \
        halo.png

      # Stack: halo → dark tubes → light tubes. Light goes on top
      # because at the central hex (where dark and light arms meet)
      # we want the brighter color to win.
      magick -size "''${maxw}x''${maxw}" canvas:none \
        halo.png       -compose screen -composite \
        tube-dark.png  -compose over   -composite \
        tube-light.png -compose over   -composite \
        neon.png

      # ---------- 4. Generate per-frame brightness schedule ----------
      # Deterministic PRNG (linear congruential, seeded with 1) so the
      # output is reproducible across rebuilds.
      awk -v n="$nframes" 'BEGIN{
        srand(1);
        # Bias toward 1.0 (steady). Each frame independently picks a
        # multiplier; consecutive low values naturally form short
        # "buzz" bursts. Tweaking these probabilities here changes the
        # whole feel — keep dim events RARE.
        for (i = 0; i < n; i++) {
          r = rand();
          if      (r < 0.005) m = 0.25;   # near-blackout, very rare
          else if (r < 0.025) m = 0.55;   # hard dim
          else if (r < 0.060) m = 0.70;   # noticeable dim
          else if (r < 0.110) m = 0.85;   # subtle flicker
          else                m = 1.00;   # steady
          printf "%.3f\n", m;
        }
      }' > schedule.txt

      # ---------- 5. Render frames ----------
      i=0
      while IFS= read -r m; do
        printf -v fname "frame-%04d.png" "$i"
        # Multiply neon RGB by m, keep alpha unchanged, then composite
        # over the background. `-channel RGB` scopes the multiply to
        # color channels only (otherwise alpha would also dim, which
        # would let the dark background bleed through and the snowflake
        # would shrink rather than just dim — the wrong perceptual
        # effect for a flickering sign).
        magick neon.png \
          -channel RGB -evaluate Multiply "$m" +channel \
          \( background.png \) +swap \
          -compose over -composite \
          "$fname"
        i=$((i + 1))
      done < schedule.txt

      # ---------- 6. Quantize ----------
      pngquant --ext .png --force --quality=60-90 --strip frame-*.png || true

      mv frame-*.png "$out/"

      echo "infinite-frames: rendered $i frames at ''${maxw}px wide" >&2
      du -sh "$out" >&2
    '';

  infiniteTheme = pkgs.runCommand "plymouth-theme-infinite" { } ''
    mkdir -p $out/share/plymouth/themes/infinite
    cp ${./theme}/infinite.plymouth $out/share/plymouth/themes/infinite/
    cp ${./theme}/infinite.script   $out/share/plymouth/themes/infinite/
    cp ${infiniteFrames}/frame-*.png $out/share/plymouth/themes/infinite/
  '';

in
{
  options.ringofstorms.plymouth = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the custom 'infinite' Plymouth boot/shutdown splash.";
    };

    frameCount = lib.mkOption {
      type = lib.types.ints.positive;
      default = 60;
      description = ''
        Number of flicker frames to generate. Played back at the fps
        baked into infinite.script (15 fps → 60 frames = 4 s loop).
        Higher = smoother / more variety in the flicker pattern,
        larger initrd. Each quantized PNG is ~50–200 KB depending
        on maxWidth.
      '';
    };

    maxWidth = lib.mkOption {
      type = lib.types.ints.positive;
      default = 1080;
      description = ''
        Frame width (and height — frames are square). The neon stack
        gets blurry-but-acceptable downscale-on-display for hosts with
        wider screens; the glow blur radii are tuned for ~1080. If you
        bump this, also bump the blur sigmas in default.nix or the
        glow will look tight/anemic at the new size.
      '';
    };

    quiet = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Suppress kernel and udev log spam so the splash is clean.
        Esc still toggles between splash and live logs at runtime
        (Plymouth's built-in behavior; we don't pass anything that
        would disable it).
      '';
    };

    earlyKms = lib.mkOption {
      type = lib.types.nullOr (lib.types.listOf lib.types.str);
      default = null;
      defaultText = lib.literalMD ''
        Auto-detected from `services.xserver.videoDrivers`:
        - `[ "amdgpu" ]` if `amdgpu` is in `videoDrivers`
        - `[ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ]` if `nvidia`
        - `[ "i915" ]` otherwise
      '';
      example = [ "amdgpu" ];
      description = ''
        KMS driver modules to force-load early in initrd so Plymouth
        has a DRM device to render against from the very first frame.

        Without this, Plymouth's framebuffer-only fallback path
        sometimes loses the race against the kernel's TTY/journal
        output, producing a text-mode boot even when the splash is
        otherwise fully configured. Loading the GPU driver in initrd
        ensures DRM is up before plymouth-start.service runs.

        When unset (the default), the value is auto-derived from
        `services.xserver.videoDrivers` so AMD/NVIDIA hosts don't
        silently inherit the wrong driver. Override explicitly when
        the heuristic guesses wrong:
          - NVIDIA proprietary: [ "nvidia" "nvidia_modeset"
                                  "nvidia_uvm" "nvidia_drm" ]
          - AMD: [ "amdgpu" ]
          - Intel: [ "i915" ]
          - Empty list (`[ ]`) disables this and relies on
            simpledrm / efifb.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    boot.plymouth = {
      enable = true;
      theme = "infinite";
      themePackages = [ infiniteTheme ];

      # Bump DeviceTimeout from upstream's 8s. On a cold boot, the real
      # KMS driver (i915 / amdgpu) can take 4–7 s to probe a panel; if
      # plymouthd hits 8 s while still on the dumb framebuffer it bails
      # to text mode for the rest of the boot. 20 s is comfortably above
      # any sane probe time and only matters when something is genuinely
      # wrong (in which case Esc still toggles to logs).
      #
      # ShowDelay=0 is also set by upstream's default extraConfig; we
      # leave that alone.
      extraConfig = ''
        DeviceTimeout=20
      '';
    };

    # ---- Kernel command line ----
    # Two flavors:
    #   1. Race-mitigation params: always on when plymouth is enabled —
    #      they don't suppress logs, they just keep the kernel and
    #      Plymouth from fighting over the framebuffer.
    #   2. Quiet/log-suppression params: only when cfg.quiet is true.
    #
    # We deliberately do NOT set `rd.systemd.show_status=false` or
    # `systemd.show_status=false` — those would disable the Esc toggle.
    boot.kernelParams =
      [
        # Don't let fbcon scroll on the framebuffer between simpledrm
        # coming up and plymouth attaching. Without this, the kernel can
        # paint text on the very same FB Plymouth is about to claim,
        # which on some boots leaves the splash invisible behind a wall
        # of journal lines.
        "fbcon=nodefer"
        # Prefer the simpledrm renderer. simpledrm works the moment any
        # framebuffer exists (efifb / firmware GOP), instead of waiting
        # for the real KMS driver to probe. Combined with DeviceTimeout
        # above, this is the single most effective fix for "the splash
        # sometimes drops to logs".
        "plymouth.use-simpledrm"
      ]
      ++ lib.optionals cfg.quiet [
        "quiet"
        "loglevel=3"
        "rd.udev.log_level=3"
        "udev.log_level=3"
        "vt.global_cursor_default=0"
        # `splash` is added by boot.plymouth automatically.
      ];

    boot.consoleLogLevel = lib.mkIf cfg.quiet 0;
    boot.initrd.verbose  = lib.mkIf cfg.quiet false;

    # ---- Force-load the GPU driver in initrd ----
    # Without this Plymouth's framebuffer fallback can lose the race
    # against the kernel's TTY/journal output, producing a text-mode
    # boot. Shutdown still works because by then the driver is loaded.
    # See `resolvedEarlyKms` in the let-block for the auto-detection
    # logic — set ringofstorms.plymouth.earlyKms explicitly to override.
    boot.initrd.kernelModules = resolvedEarlyKms;

    # ---- Initrd: order plymouth-start ahead of the password prompt ----
    # The bcachefs unlock service issues a `systemd-ask-password` call
    # in stage 1. If `systemd-ask-password-console.service` activates
    # before `systemd-ask-password-plymouth.path` is up, the console
    # agent claims /dev/console and the prompt goes to text — and from
    # that moment the splash never reappears for the rest of boot.
    #
    # We pin the ordering: plymouth-start runs before the unlock service
    # and before the console password agent could ever fire, and we
    # eagerly start the plymouth ask-password path unit at sysinit so
    # any prompt is intercepted before the console agent sees it.
    #
    # `lib.mkIf config.boot.initrd.systemd.enable` so a host that
    # somehow disables systemd-initrd doesn't trip on a missing unit.
    boot.initrd.systemd = lib.mkIf config.boot.initrd.systemd.enable {
      services.plymouth-start = {
        wantedBy = [ "initrd.target" ];
        before = [
          "sysroot.mount"
          "initrd-root-fs.target"
          "systemd-ask-password-console.service"
          "unlock-bcachefs-custom.service"
        ];
      };
      paths.systemd-ask-password-plymouth = {
        wantedBy = [ "sysinit.target" ];
      };
    };

    # ---- Stage 2: keep vconsole-setup off Plymouth's surface ----
    # `console.earlySetup = true` (set by tty_caps_esc.nix) makes
    # systemd-vconsole-setup.service run very early in stage 2. It
    # reprograms VT1 (font, palette) which can blank the surface
    # Plymouth currently owns. Two complementary mitigations:
    #   a. Disable earlySetup whenever Plymouth is active. The Caps→Esc
    #      keymap from tty_caps_esc still applies, just a beat later
    #      during the regular vconsole-setup pass.
    #   b. Make the regular vconsole-setup pass wait until Plymouth has
    #      handed off (plymouth-quit-wait completes when the renderer
    #      releases DRM master).
    console.earlySetup = lib.mkForce false;
    systemd.services.systemd-vconsole-setup = {
      after = [ "plymouth-quit-wait.service" ];
    };

    # Give plymouth-quit-wait headroom on slow KMS handovers (matches
    # the bumped DeviceTimeout above; default is 10 s).
    systemd.services.plymouth-quit-wait.serviceConfig.TimeoutStopSec = "20";

    # Plymouth requires systemd-initrd for clean integration. The
    # impermanence module already enables this; assert here so a
    # non-impermanence host enabling Plymouth gets a clear failure
    # instead of a silent broken splash.
    assertions = [
      {
        assertion = config.boot.initrd.systemd.enable;
        message = ''
          ringofstorms.plymouth requires boot.initrd.systemd.enable = true.
          Either enable the impermanence module (which enables it) or set
          this directly in your host config.
        '';
      }
    ];
  };
}
